s1 = str("Орлов")
s2 = str("Дмитрий*Дмитрий*Дмитрий*Дмитрий")
s3 = str("Васильевич")
s4 = str("Ноябрь")
print('s1= ', s1)
print('s2= ', s2)
print('s3= ', s3)
print('s4= ', s4)
print('s1+s2= ', s1 + s2)
print('s1*3= ', s1 * 3)
print('s1[2]= ', s1[2])
print('s1[2:4]= ', s1[2:4])
print('s3.count= ', s3.count(s2))
print('s1.find "о"= ', s1.find('о'))
# print('s1.index("п")',s1.index('п'))
# print('s1.rindex("c")',s1.rindex("д"))
print('s4.replace(о,а)= ',s4.replace("о","а"))
print('s2.split("*")',s2.split('*'))
print("s1.upper()",s1.upper())
print('s1.lower()',s1.lower())
